# Generated by Django 5.1.1 on 2024-09-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_doctor', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_patient', to='users.patient'),
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient', 'consultation_date'), name='unique_consultation'),
        ),
    ]
