# Generated by Django 5.1.1 on 2024-09-26 21:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(default=datetime.datetime(2024, 9, 26, 15, 1, 16, 295831, tzinfo=datetime.timezone.utc), help_text='Consultation current time')),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In-progress'), ('completed', 'Completed')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_doctor', to='users.doctor')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='CommonConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, help_text="Patient's medical diagnosis", max_length=255, null=True, verbose_name='Diagnosis')),
                ('test_applied', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], help_text="Patient's required tests?", null=True, verbose_name='Analysis applied')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('urgency', 'Urgency'), ('regular', 'Regular')], max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UrgencyConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_symptom', models.CharField(help_text="Patient's main symptom", max_length=255, verbose_name='Main synptom')),
                ('admitted', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], help_text="Patient's required admission?", null=True, verbose_name='Admitted')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's body temperature in degrees Celsius", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(36.5), django.core.validators.MaxValueValidator(42.5)], verbose_name='Body temperature')),
                ('pulse', models.IntegerField(blank=True, help_text="Patient's pulse rate in beats per minute", null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)], verbose_name='Pulse Rate')),
                ('systolic_pressure', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's systolic blood pressure in mmHg", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(140)], verbose_name='Systolic Blood Pressure')),
                ('diastolic_pressure', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's diastolic blood pressure in mmHg", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(90)], verbose_name='Diastolic Blood Pressure')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('doctor', 'consultation_date'), name='unique_consultation'),
        ),
    ]
