# Generated by Django 5.1.1 on 2024-09-23 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 17, 18, 8, 572444, tzinfo=datetime.timezone.utc)),
        ),
    ]
