# Generated by Django 5.1.1 on 2024-09-23 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_consultation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
