# Generated by Django 5.1.1 on 2024-09-29 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_consultation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 14, 19, 9, 926476, tzinfo=datetime.timezone.utc), help_text='Consultation current time'),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='consultation_type',
            field=models.CharField(choices=[('urgency', 'Urgency'), ('common', 'Common')], max_length=20),
        ),
    ]
