# Generated by Django 5.1.1 on 2024-10-09 21:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultation_consultation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 15, 10, 43, 196257, tzinfo=datetime.timezone.utc), help_text='Consultation current time'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='diastolic_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages='Please, select a value between 60 and 90', help_text="Patient's diastolic blood pressure in mmHg", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(90)], verbose_name='Diastolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='pulse',
            field=models.IntegerField(blank=True, error_messages='Please, select a value between 40 and 120', help_text="Patient's pulse rate in beats per minute", null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)], verbose_name='Pulse Rate'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='systolic_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages='Please, select a value between 90 and 140', help_text="Patient's systolic blood pressure in mmHg", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(140)], verbose_name='Systolic Blood Pressure'),
        ),
    ]
