# Generated by Django 5.1.1 on 2024-10-09 21:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultation_consultation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 15, 11, 34, 639494, tzinfo=datetime.timezone.utc), help_text='Consultation current time'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages='Please, select a value between 36.5 and 42.5', help_text="Patient's body temperature in degrees Celsius", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(36.5), django.core.validators.MaxValueValidator(42.5)], verbose_name='Body temperature'),
        ),
    ]
