# Generated by Django 5.1.1 on 2024-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/picture_profiles/default_profile_picture2.png', help_text='Upload a profile picture', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
