# Generated by Django 5.1.1 on 2024-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static img/picture_profiles/default_profile_picture2.png', help_text='Upload a profile picture', null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
